RICO_PATTERN_STRING = r"""(?P<stock_exchange>(?:\w|-)+)
                    (?P<buy_or_sell>C|V)
                    (?P<market>\w+)
                    (?P<stock>.+)(?P<obs>(\n\w)?)
                    (?P<amount>(?:\d{0,3}\.)*\d{0,3})
                    (?P<price>(?:\d{0,3}\.)*\d{0,3},\d{2})
                    (?P<total>(?:\d{0,3}\.)*\d{0,3},\d{2})
                    (?P<credit_or_debit>D|C)"""

RICO_BROKERAGE_RECEIPT_PATTERN_STRING = r"""(?P<total_cblc>(?:\d{0,3}\.)*\d{0,3},\d{2})
(?:.+?)
(?:[DC])
(?P<net_operation_value>(?:\d{0,3}\.)*\d{0,3},\d{2})
(?:.+?)
(?:[DC])
(?P<liquidation_fee>(?:\d{0,3}\.)*\d{0,3},\d{2})
(?:.+?)
(?:[DC])
(?P<registration_fee>(?:\d{0,3}\.)*\d{0,3},\d{2})
(?:.+?)
(?:[DC])
(?P<total_bovespa>(?:\d{0,3}\.)*\d{0,3},\d{2})
(?:.+?)
(?:[DC])
(?P<options_fee>(?:\d{0,3}\.)*\d{0,3},\d{2})
(?:.+?)
(?:[DC])
(?P<ana_total>(?:\d{0,3}\.)*\d{0,3},\d{2})
(?:.+?)
(?:[DC])
(?P<emoluments>(?:\d{0,3}\.)*\d{0,3},\d{2})
(?:.+?)
(?:[DC])
 
(?P<total_costs>(?:\d{0,3}\.)*\d{0,3},\d{2})
(?:.+?)
(?:[DC])
 
(?P<operational_fee>(?:\d{0,3}\.)*\d{0,3},\d{2})
(?:.+?)
(?:[DC])
(?P<execution>(?:\d{0,3}\.)*\d{0,3},\d{2})
(?:.+?)
(?P<custody_fee>(?:\d{0,3}\.)*\d{0,3},\d{2})
(?:.+?)
(?P<taxes>(?:\d{0,3}\.)*\d{0,3},\d{2})
(?:.+?)
(?P<irrf_wo_operation>(?:\d{0,3}\.)*\d{0,3},\d{2})
(?:.+?)
(?P<others>(?:\d{0,3}\.)*\d{0,3},\d{2})
(?:.+?)
(?:[DC])
(?P<net_value_for_date>(?:\d{0,3}\.)*\d{0,3},\d{2})
(?:.+?)
(?:[DC])
"""
